export type ProjectCategory =
  | "Residential"
  | "Administrative"
  | "Retail"
  | "Commercial"
  | "Mixed";

export interface Project {
  id: string;
  name: string;
  developer: string;
  country: string;
  city: string;
  district: string;
  category: ProjectCategory[];
  commission_scheme: number;
  units_remaining: number;
  total_units: number;
  units_sold: number;
  description: string;
  photos: string[];
}

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "7182072b-30c4-41d3-a7a3-587a5e05ced7",
    name: "Sky Gardens",
    developer: "Mountain View",
    country: "Egypt",
    city: "Cairo",
    district: "Nasr City",
    category: ["Residential"],
    commission_scheme: 4.25,
    units_remaining: 43,
    total_units: 180,
    units_sold: 137,
    description:
      "Sky Gardens is a residential development located in Nasr City.",
    photos: ["https://cdn.example.com/properties/sky-gardens/featured.jpg"],
  },
  {
    id: "6bade7f8-4ee4-4d01-ace7-2af80d2fbad6",
    name: "Crystal Heights",
    developer: "Emaar Misr",
    country: "Egypt",
    city: "Giza",
    district: "Sheikh Zayed",
    category: ["Mixed"],
    commission_scheme: 4.15,
    units_remaining: 529,
    total_units: 600,
    units_sold: 71,
    description:
      "Crystal Heights is a mixed-use development located in Sheikh Zayed.",
    photos: ["https://cdn.example.com/properties/crystal-heights/featured.jpg"],
  },
  {
    id: "a598620b-9fe5-4bfa-8b6f-f1cfb0a16b1f",
    name: "Stone Residence",
    developer: "Talaat Moustafa Group",
    country: "Egypt",
    city: "Cairo",
    district: "New Administrative Capital",
    category: ["Residential"],
    commission_scheme: 5.43,
    units_remaining: 1,
    total_units: 1200,
    units_sold: 1199,
    description:
      "Stone Residence is a residential development located in New Administrative Capital.",
    photos: ["https://cdn.example.com/properties/stone-residence/featured.jpg"],
  },
  {
    id: "5f819ed6-0942-45d8-bdb4-f0479ab71989",
    name: "Royal Towers",
    developer: "LMD",
    country: "Egypt",
    city: "Cairo",
    district: "Nasr City",
    category: ["Retail"],
    commission_scheme: 4.95,
    units_remaining: 780,
    total_units: 900,
    units_sold: 120,
    description: "Royal Towers is a retail development located in Nasr City.",
    photos: ["https://cdn.example.com/properties/royal-towers/featured.jpg"],
  },
  {
    id: "01c5b0b8-b10a-42ec-a069-b67bc42704b4",
    name: "Stone Hills",
    developer: "Marakez",
    country: "Egypt",
    city: "Cairo",
    district: "New Administrative Capital",
    category: ["Administrative"],
    commission_scheme: 2.68,
    units_remaining: 40,
    total_units: 180,
    units_sold: 140,
    description:
      "Stone Hills is a administrative development located in New Administrative Capital.",
    photos: ["https://cdn.example.com/properties/stone-hills/featured.jpg"],
  },
  {
    id: "533b5b4e-a6ea-4795-8f07-61c5123a995b",
    name: "Silver Park",
    developer: "Mountain View",
    country: "Egypt",
    city: "Cairo",
    district: "Nasr City",
    category: ["Administrative"],
    commission_scheme: 3.4,
    units_remaining: 151,
    total_units: 750,
    units_sold: 599,
    description:
      "Silver Park is a administrative development located in Nasr City.",
    photos: ["https://cdn.example.com/properties/silver-park/featured.jpg"],
  },
  {
    id: "f02c0ebf-532c-4e27-9f28-6ba73e82ac73",
    name: "Vista Plaza",
    developer: "Tatweer Misr",
    country: "Egypt",
    city: "Giza",
    district: "Sheikh Zayed",
    category: ["Administrative"],
    commission_scheme: 3.85,
    units_remaining: 394,
    total_units: 900,
    units_sold: 506,
    description:
      "Vista Plaza is a administrative development located in Sheikh Zayed.",
    photos: ["https://cdn.example.com/properties/vista-plaza/featured.jpg"],
  },
  {
    id: "b5360155-7c24-4f26-a9b2-d033efc5fa0e",
    name: "Green Residence",
    developer: "Hassan Allam Properties",
    country: "Egypt",
    city: "Cairo",
    district: "Nasr City",
    category: ["Retail"],
    commission_scheme: 2.62,
    units_remaining: 403,
    total_units: 480,
    units_sold: 77,
    description:
      "Green Residence is a retail development located in Nasr City.",
    photos: ["https://cdn.example.com/properties/green-residence/featured.jpg"],
  },
  {
    id: "269a467c-3ece-47f6-9865-a043da4330a1",
    name: "Palm Hills",
    developer: "Marakez",
    country: "Egypt",
    city: "Cairo",
    district: "Heliopolis",
    category: ["Administrative"],
    commission_scheme: 4.89,
    units_remaining: 176,
    total_units: 480,
    units_sold: 304,
    description:
      "Palm Hills is a administrative development located in Heliopolis.",
    photos: ["https://cdn.example.com/properties/palm-hills/featured.jpg"],
  },
  {
    id: "0fa5febb-7a83-4538-a4df-56fc8aa22a10",
    name: "Green Towers",
    developer: "Redcon",
    country: "Egypt",
    city: "Cairo",
    district: "El Shorouk",
    category: ["Residential"],
    commission_scheme: 4.23,
    units_remaining: 27,
    total_units: 120,
    units_sold: 93,
    description:
      "Green Towers is a residential development located in El Shorouk.",
    photos: ["https://cdn.example.com/properties/green-towers/featured.jpg"],
  },
  {
    id: "3d02cc34-0946-4bf9-93e8-6b7b23b0e467",
    name: "Lake Towers",
    developer: "Mountain View",
    country: "Egypt",
    city: "Cairo",
    district: "Nasr City",
    category: ["Administrative"],
    commission_scheme: 3.0,
    units_remaining: 0,
    total_units: 120,
    units_sold: 120,
    description:
      "Lake Towers is a administrative development located in Nasr City.",
    photos: ["https://cdn.example.com/properties/lake-towers/featured.jpg"],
  },
  {
    id: "16b438d2-2368-44e1-8a42-db730ed1b24a",
    name: "Grand Plaza",
    developer: "Misr Italia",
    country: "Egypt",
    city: "Cairo",
    district: "Maadi",
    category: ["Retail"],
    commission_scheme: 2.74,
    units_remaining: 97,
    total_units: 300,
    units_sold: 203,
    description: "Grand Plaza is a retail development located in Maadi.",
    photos: ["https://cdn.example.com/properties/grand-plaza/featured.jpg"],
  },
  {
    id: "57da24bd-1abc-4482-bf60-6870cb946b03",
    name: "Palm Towers",
    developer: "Mountain View",
    country: "Egypt",
    city: "Giza",
    district: "6th of October City",
    category: ["Mixed"],
    commission_scheme: 4.55,
    units_remaining: 615,
    total_units: 900,
    units_sold: 285,
    description:
      "Palm Towers is a mixed-use development located in 6th of October City.",
    photos: ["https://cdn.example.com/properties/palm-towers/featured.jpg"],
  },
  {
    id: "e33b78bc-6b8b-4c87-90f9-83ebfa15e783",
    name: "Crystal Gardens",
    developer: "Talaat Moustafa Group",
    country: "Egypt",
    city: "Giza",
    district: "Sheikh Zayed",
    category: ["Retail"],
    commission_scheme: 3.95,
    units_remaining: 181,
    total_units: 240,
    units_sold: 59,
    description:
      "Crystal Gardens is a retail development located in Sheikh Zayed.",
    photos: ["https://cdn.example.com/properties/crystal-gardens/featured.jpg"],
  },
  {
    id: "aae02b04-4127-44dd-a7c1-a5b49ffb7e26",
    name: "Park Towers",
    developer: "Marakez",
    country: "Egypt",
    city: "Cairo",
    district: "New Cairo",
    category: ["Retail"],
    commission_scheme: 4.2,
    units_remaining: 53,
    total_units: 600,
    units_sold: 547,
    description: "Park Towers is a retail development located in New Cairo.",
    photos: ["https://cdn.example.com/properties/park-towers/featured.jpg"],
  },
  {
    id: "2b11e817-c5cc-4ee8-a1f2-f179e53a8da5",
    name: "Vista Park",
    developer: "Hassan Allam Properties",
    country: "Egypt",
    city: "Cairo",
    district: "New Cairo",
    category: ["Mixed"],
    commission_scheme: 3.68,
    units_remaining: 499,
    total_units: 900,
    units_sold: 401,
    description: "Vista Park is a mixed-use development located in New Cairo.",
    photos: ["https://cdn.example.com/properties/vista-park/featured.jpg"],
  },
  {
    id: "f17ebdd0-75bc-4561-89c2-30aabbae9c4e",
    name: "Sun Heights",
    developer: "Emaar Misr",
    country: "Egypt",
    city: "Cairo",
    district: "New Administrative Capital",
    category: ["Residential"],
    commission_scheme: 3.52,
    units_remaining: 75,
    total_units: 300,
    units_sold: 225,
    description:
      "Sun Heights is a residential development located in New Administrative Capital.",
    photos: ["https://cdn.example.com/properties/sun-heights/featured.jpg"],
  },
  {
    id: "81cca3df-0521-41d1-a429-a5f285b08176",
    name: "Grand Hills",
    developer: "Emaar Misr",
    country: "Egypt",
    city: "Giza",
    district: "6th of October City",
    category: ["Residential"],
    commission_scheme: 5.12,
    units_remaining: 166,
    total_units: 480,
    units_sold: 314,
    description:
      "Grand Hills is a residential development located in 6th of October City.",
    photos: ["https://cdn.example.com/properties/grand-hills/featured.jpg"],
  },
  {
    id: "f90a5495-85d8-49d3-808f-4de76490af5e",
    name: "Royal Gate",
    developer: "Emaar Misr",
    country: "Egypt",
    city: "Cairo",
    district: "Maadi",
    category: ["Administrative"],
    commission_scheme: 2.85,
    units_remaining: 455,
    total_units: 1200,
    units_sold: 745,
    description: "Royal Gate is a administrative development located in Maadi.",
    photos: ["https://cdn.example.com/properties/royal-gate/featured.jpg"],
  },
  {
    id: "811eafb9-aa3c-4fd1-bf7f-b0930865f50c",
    name: "Lake View",
    developer: "Tatweer Misr",
    country: "Egypt",
    city: "Cairo",
    district: "El Shorouk",
    category: ["Administrative"],
    commission_scheme: 3.53,
    units_remaining: 144,
    total_units: 180,
    units_sold: 36,
    description:
      "Lake View is a administrative development located in El Shorouk.",
    photos: ["https://cdn.example.com/properties/lake-view/featured.jpg"],
  },
];
